name: Hello-Poussin

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: récupérer le code 
        uses: action/checkout@v3
      - name: afficher hello world
        run: echo Hello World
